### ISSUE TITLE
Checklist of collection level metadata fields requested for DarwinCore/EMODnet export

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_dev#527]
Requested fields are listed, the required ones marked with a *, action for each field is 

- [x] **Person providing metadata**: (@grololo06 : is it actually required). Defaults to contact person. _Nothing to do_

- [x] **Dataset title** * = project/collection title, _nothing to do_

- [x] **Contact person** *: To be added for all projects, in project settings. Chose among the managers of the project; only one person among them. The manager status of that person cannot be changed.

- [x] **Data creators** *: will be listed alphabetically in the project page on EMODnet. Default to the combination of:
     - all users currently listed as annotators
     - all users having done > 10% of all annotations on the project (all annotations include current and historical ones; this stat should be available from the About project page #382 )
_To implement_

- [x] **Associated person** (will not be listed): Do we allow it or just leave it empty? I am in favour of forgetting about it. You contribute => you're cited.

- [x] **Dataset citation** *: free text. Defaults to "Contact person, project title"

- [x] **Licence** *: fields exists, nothing to do.
- [x] **Abstract** * : 1000 char max; about the content of the dataset => use project description. _Nothing to do._
- [ ] **Description** : longer description, if need be; do we use it? If we do, we should change the name of description to abstract.
- [x] **Geographical coverage** *: bounding box of sample/subsample/object lat lon
- [x] **Temporal coverage** *: limites of sample/subsample/object date
- [x] **Taxonomic coverage** *: list of all taxa with aphiaIDs.
- [x] **Functional groups** *: plankton
- [x] **Keywords** * : plankton, imaging, ecotaxa, `name of instrument`
- [x] **Websites**: EcoTaxa project URL
- [x] **Publications** (describing the dataset or based on the dataset): Do we allow it?

**Comment by grololo06** [comment]
Let's do it at collection level and aggregate enclosed projects data into the collection at creation/update time. This way, users not needing/wanting to do Dwca will not be annoyed.
Example aggregation (already coded): license = most restrictive of all projects licenses. https://github.com/ecotaxa/ecotaxa_back/commit/310ac430b75112746e9d36d7ce7db713fe1da22a

**Comment by picheral** [comment]
OK to do it at collection level... but we should encourage and facilitate the creation of the Collections.

Small remark. I would add "Particles" to  Keywords.
